#include <stdio.h>

/*
 * This is very simple, faux legacy C code with lots of ugly corners (or which
 * is basically one giant ugly corner). The only purpose of this code is to
 * help me walk along the examples of the somewhat out-of-date "J for C
 * programmers" book.
 */

#define NEMP 4
#define NCLIENTS 3

int empno[NEMP] = { 316, 317, 319, 320 };
int payrate[NEMP] = { 60, 42, 44, 54 };
int billrate[NEMP] = { 120, 90, 90, 108 };
int clientlist[NCLIENTS] = { 10011, 10012, 10025 };
int emp_client[NEMP] = { 10012, 10025, 10012, 10025 };

int hoursworked[NEMP][31] = {
    {8, 0, 3, 10, 9, 8, 8, 9, 4, 0, 8, 7, 10, 10, 12, 9, 0, 6, 8, 9, 9, 9, 0, 0, 10, 11, 9, 7, 10, 2, 0},
    {8, 0, 0, 9, 9, 8, 9, 10, 0, 0, 8, 8, 10, 7, 10, 0, 0, 7, 8, 9, 8, 9, 0, 4, 9, 8, 9, 8, 9, 0, 0},
    {5, 0, 0, 8, 9, 9, 9, 9, 0, 0, 8, 7, 0, 0, 9, 0, 2, 10, 10, 9, 11, 8, 0, 0, 8, 9, 10, 8, 9, 0, 0},
    {9, 0, 0, 9, 10, 8, 6, 6, 8, 0, 9, 8, 10, 6, 9, 7, 0, 6, 8, 8, 8, 9, 0, 5, 8, 9, 8, 8, 12, 0, 0},
};

/* Finds the number of hours each employee worked in the given month. */
void emphours(int hrs[]) {
    int i, j;
    for (i = 0; i < NEMP; ++i) {
        for (j = 0; j < 31; ++j) {
            hrs[i] += hoursworked[i][j];
        }
    }
}

/* Determines the wages earned by each employee in the given month. */
void empearnings(int earns[]) {
    int i, j;
    for (i = 0; i < NEMP; ++i) {
        for (j = 0; j < 31; ++j) {
            earns[i] += hoursworked[i][j];
        }
        earns[i] *= payrate[i];
    }
}

/* Determines the profit brought in by each employee. */
void empprofit(int profit[]) {
    int i, j, temp;
    for (i = 0; i < NEMP; ++i) {
        for (j = 0, temp = 0; j < 31; ++j) {
            temp += hoursworked[i][j];
        }
        profit[i] = temp * (billrate[i] - payrate[i]);
    }
}

/* Returns the amount to bill a given client. */
int billclient(int cno)
{
    int i, j, temp, total;
    total = 0;
    for (i = 0; i < NEMP; ++i) {
        if (emp_client[i] == cno) {
            for (j = 0, temp = 0; j < 31; ++j) {
                temp += hoursworked[i][j];
            }
            total += billrate[i] * temp;
        }
    }
    return total;
}

/* Finds for each day of the month the employee who billed the most hours. */
void dailydrudge(int drudges[31])
{
    int i, j, highhours;
    for (i = 0; i < 31; ++i) {
        highhours = -1;
        for (j = 0; j < NEMP; ++j) {
            if (hoursworked[j][i] > highhours) {
                drudges[i] = empno[j];
                highhours = hoursworked[j][i];
            }
        }
    }
}

/* Returns the employees, in descending order of the profit brought in by each. */
void producers(int prods[])
{
    int i, j, max, maxprofit;
    int profits[NEMP];
    empprofit(profits);

    /* Since this is a toy program we can afford selection sort. */
    for (i = 0; i < NEMP; ++i) {
        maxprofit = -1;
        for (j = 0, max = 0; j < NEMP; ++j) {
            if (profits[j] > maxprofit) {
                max = j;
                maxprofit = profits[j];
            }
        }
        prods[i] = empno[max];
        profits[max] = -1;
    }
}

/* Returns the clients, in descending order of the profit generated by each. */
void custbyprofit(int clients[])
{
    int i, j, k, maxprofit;
    int profits[NEMP];
    int clientprofits[NCLIENTS];
    for (i = 0; i < NCLIENTS; ++i) {
        clientprofits[i] = 0;
    }

    empprofit(profits);
    for (i = 0; i < NEMP; ++i) {
        k = -1;
        for (j = 0; j < NCLIENTS; ++j) {
            if (clientlist[j] == emp_client[i]) {
                k = j;
                break;
            }
        }
        clientprofits[k] += profits[i];
    }

    for (i = 0; i < NCLIENTS; ++i) {
        k = -1;
        maxprofit = -1;
        for (j = 0; j < NCLIENTS; ++j) {
            if (clientprofits[j] > maxprofit) {
                k = j;
                maxprofit = clientprofits[j];
            }
        }
        clients[i] = clientlist[k];
        clientprofits[k] = -1;
    }
}

/* TODO work in progress*/
int renderuntocaesar(float shekels[])
{
    int bktmin[4] = {0, 6000, 10000, 50000};
    float bktrate[3] = {0.05, 0.10, 0.20};
    int i, j;
    int earns[NEMP];
    for (i = 0; i < NEMP; ++i) {
        earns[i] = 0;
    }

    /* Slightly less capitalist than book example: do not cap high income taxes. */
    empearnings(earns);
    for (i = 0; i < NEMP; ++i) {
        shekels[i] = 0.0;
        for (j = 0; j < sizeof(bktrate)/sizeof(bktrate[0]); ++j) {
            if (earns[i] > bktmin[j]) {
                int bktval = bktmin[j+1];
                if (earns[i] < bktval) {
                    bktval = earns[i];
                }
                shekels[i] += (bktval - bktmin[j]) * bktrate[j]; /* TODO check */
            }
        }
    }
}

int main(int argc, char *argv[])
{
    int i;

    printf("Problem 1\n");
    int hrs[NEMP];
    emphours(hrs);
    for (i = 0; i < NEMP-1; i++) {
        printf("%d ", hrs[i]);
    }
    printf("%d\n", hrs[NEMP-1]);

    printf("Problem 2\n");
    int earns[NEMP];
    empearnings(earns);
    for (i = 0; i < NEMP-1; i++) {
        printf("%d ", earns[i]);
    }
    printf("%d\n", earns[NEMP-1]);

    printf("Problem 3\n");
    int profit[NEMP];
    empprofit(profit);
    for (i = 0; i < NEMP-1; i++) {
        printf("%d ", profit[i]);
    }
    printf("%d\n", profit[NEMP-1]);

    printf("Problem 4\n");
    int clientno = 10025;
    printf("%d\n", billclient(clientno));

    printf("Problem 5\n");
    int drudges[31];
    dailydrudge(drudges);
    for (i = 0; i < 30; i++) {
        printf("%d ", drudges[i]);
    }
    printf("%d\n", drudges[30]);

    printf("Problem 6\n");
    int prods[NEMP];
    producers(prods);
    for (i = 0; i < NEMP-1; i++) {
        printf("%d ", prods[i]);
    }
    printf("%d\n", prods[i]);

    printf("Problem 7\n");
    int clients[NCLIENTS];
    custbyprofit(clients);
    for (i = 0; i < NCLIENTS-1; i++) {
        printf("%d ", clients[i]);
    }
    printf("%d\n", clients[i]);

    printf("Problem 8\n");
    float shekels[NEMP];
    renderuntocaesar(shekels);
    for (i = 0; i < NEMP-1; i++) {
        printf("%.2f ", shekels[i]);
    }
    printf("%.2f\n", shekels[i]);

    return 0;
}
